function(bnio_add_base_example name source)
  add_executable(bnio_base_${name} ${source})
  target_link_libraries(bnio_base_${name} PRIVATE bnio::bnio)
  bnio_set_project_warnings(bnio_base_${name})
endfunction()

bnio_add_base_example(nop nop.cpp)
bnio_add_base_example(probe probe.cpp)
bnio_add_base_example(timeout timeout.cpp)
bnio_add_base_example(poll poll.cpp)
bnio_add_base_example(echo_server echo_server.cpp)
