if(BNIO_PLATFORM_LINUX OR BNIO_PLATFORM_BSD)
  add_subdirectory(mini_curl)
  add_subdirectory(echo_server)
  add_subdirectory(dns_lookup)
  add_subdirectory(tcp_client)
  add_subdirectory(timer_chain)
  add_subdirectory(timer_cancel)
  add_subdirectory(udp_echo)
  add_subdirectory(udp_connected)
  add_subdirectory(poll_fd)
  add_subdirectory(file_cat)
endif()
